"""
THE country table — the one place the codebase knows what a country is called.

Seed: ``countries.json`` is the World Bank country list (aggregates removed), regenerated by
``newsroom actors registry --write``; it is plain data. Curation lives here in code: the common English
name where the Bank's differs ("Russian Federation" -> "Russia"), aliases other names go by, which
entries are territories rather than states (ranked only against states), and the two entries the Bank
lacks (Taiwan, the European Union). Everything else — flags, profile pages, the Actors publish, the
renderer in ``publishing/tagging.py`` — asks this module.

Resolution (``resolve``) turns a NAME AN AGENT ALREADY CHOSE ("Russia", "U.S.", "United Kingdom")
into an ISO2 code. It is never used to scan stories for countries: geography is a semantic judgment
the researcher makes (see ``publishing/tagging.py``); this only renders it. A name that is not exactly
a country's name or alias resolves to None.
"""

from __future__ import annotations

import json
import re
from functools import lru_cache
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel

_SEED = Path(__file__).with_name("countries.json")
_NON_WORD = re.compile(r"[^a-z0-9]+")

Kind = Literal["state", "territory", "bloc"]

#: Common English name where it differs from the World Bank's.
NAMES: dict[str, str] = {
    "BS": "Bahamas", "CD": "Democratic Republic of the Congo", "CG": "Republic of the Congo",
    "EG": "Egypt", "FM": "Micronesia", "GM": "Gambia", "HK": "Hong Kong", "IR": "Iran",
    "KG": "Kyrgyzstan", "KR": "South Korea", "KP": "North Korea", "LA": "Laos", "MO": "Macao",
    "RU": "Russia", "SK": "Slovakia", "SO": "Somalia", "SY": "Syria", "TR": "Turkey", "VE": "Venezuela",
    "YE": "Yemen", "CZ": "Czechia", "CV": "Cape Verde", "MM": "Myanmar", "VN": "Vietnam",
    "BN": "Brunei", "ST": "Sao Tome and Principe", "KN": "Saint Kitts and Nevis", "VC": "Saint Vincent and the Grenadines",
    "LC": "Saint Lucia", "SZ": "Eswatini", "TL": "Timor-Leste", "PS": "Palestine", "XK": "Kosovo",
    "US": "United States", "GB": "United Kingdom", "CI": "Cote d'Ivoire", "MK": "North Macedonia",
}

#: Other names a country is known by (matched exactly after normalising case and punctuation).
ALIASES: dict[str, tuple[str, ...]] = {
    "US": ("USA", "U.S.", "U.S.A.", "US", "United States of America", "America"),
    "GB": ("UK", "U.K.", "Britain", "Great Britain", "United Kingdom of Great Britain and Northern Ireland"),
    "RU": ("Russian Federation",), "IR": ("Islamic Republic of Iran", "Persia"),
    "KR": ("Republic of Korea", "Korea", "South Korea"), "KP": ("DPRK", "Democratic People's Republic of Korea"),
    "TR": ("Turkiye", "Türkiye"), "SY": ("Syrian Arab Republic",), "CZ": ("Czech Republic",),
    "MM": ("Burma",), "CV": ("Cabo Verde",), "CI": ("Ivory Coast",), "SZ": ("Swaziland",), "TL": ("East Timor",),
    "MK": ("Macedonia",), "VE": ("Bolivarian Republic of Venezuela",), "LA": ("Lao PDR",),
    "CD": ("DR Congo", "DRC", "Congo-Kinshasa"), "CG": ("Congo-Brazzaville",),
    "TW": ("Republic of China", "Chinese Taipei"), "AE": ("UAE", "U.A.E."), "VN": ("Viet Nam",),
    "PS": ("Palestinian territories", "State of Palestine"), "EU": ("EU", "E.U.", "European Union"),
    "NL": ("Holland",),
}

#: World Bank entries that are not sovereign states (ranked only against states).
TERRITORIES = frozenset({
    "AS", "AW", "BM", "CW", "FO", "GI", "GL", "GU", "HK", "IM", "JG", "KY", "MF", "MO", "MP", "NC", "PF",
    "PR", "PS", "SX", "TC", "VG", "VI",
})

#: The standing set a published actor list always carries: the G20's states and the UN Security Council's P5.
G20 = ("AR", "AU", "BR", "CA", "CN", "FR", "DE", "IN", "ID", "IT", "JP", "KR", "MX", "RU", "SA", "ZA", "TR", "GB", "US")
UNSC_P5 = ("US", "RU", "CN", "GB", "FR")

#: Entries the World Bank list lacks (it has no Taiwan; its European Union is an aggregate).
_EXTRA = (
    {"iso2": "TW", "iso3": "TWN", "wb_name": "Taiwan", "region": "East Asia & Pacific", "capital": "Taipei", "kind": "state"},
    {"iso2": "EU", "iso3": "EUU", "wb_name": "European Union", "region": "Europe & Central Asia", "capital": "Brussels", "kind": "bloc"},
)


class Country(BaseModel):
    iso2: str
    iso3: str
    name: str
    region: str = ""
    capital: str = ""
    kind: Kind = "state"
    aliases: list[str] = []


def _norm(text: str) -> str:
    return _NON_WORD.sub(" ", (text or "").casefold().replace("’", "'")).strip()


def build_rows(wb_countries: list[dict[str, Any]]) -> list[dict[str, str]]:
    """Seed rows from the World Bank ``/country`` list: aggregates ("World", "Euro area") dropped."""
    rows = []
    for c in wb_countries:
        region = (c.get("region") or {}).get("value", "").strip()
        iso2 = c.get("iso2Code", "")
        if not region or region == "Aggregates" or len(iso2) != 2:
            continue
        rows.append({"iso2": iso2, "iso3": c["id"], "wb_name": c["name"].strip(), "region": region,
                     "capital": (c.get("capitalCity") or "").strip(), "kind": "territory" if iso2 in TERRITORIES else "state"})
    return sorted(rows, key=lambda r: r["iso2"])


def write_seed(rows: list[dict[str, str]]) -> Path:
    _SEED.write_text(json.dumps(rows, ensure_ascii=False, indent=1) + "\n", encoding="utf-8", newline="\n")
    load.cache_clear()
    return _SEED


@lru_cache(maxsize=1)
def load() -> dict[str, Country]:
    """Every entry by ISO2: the seed plus the curated extras, with common names applied."""
    seed = json.loads(_SEED.read_text(encoding="utf-8"))
    have = {r["iso2"] for r in seed}
    out: dict[str, Country] = {}
    for r in [*seed, *(e for e in _EXTRA if e["iso2"] not in have)]:
        iso2 = r["iso2"]
        out[iso2] = Country(iso2=iso2, iso3=r["iso3"], name=NAMES.get(iso2, r["wb_name"]), region=r["region"],
                            capital=r["capital"], kind=r["kind"],
                            aliases=[a for a in (r["wb_name"], *ALIASES.get(iso2, ())) if a != NAMES.get(iso2, r["wb_name"])])
    return out


@lru_cache(maxsize=1)
def _index() -> dict[str, str]:
    idx: dict[str, str] = {}
    for c in load().values():
        for label in (c.name, *c.aliases):
            idx.setdefault(_norm(label), c.iso2)
    for c in load().values():             # a code is only an alias when it does not shadow a name
        idx.setdefault(_norm(c.iso2), c.iso2)
        idx.setdefault(_norm(c.iso3), c.iso2)
    return idx


def get(iso2: str) -> Country | None:
    return load().get((iso2 or "").strip().upper())


def display_name(iso2: str, default: str = "") -> str:
    c = get(iso2)
    return c.name if c else default


def resolve(text: str) -> str | None:
    """ISO2 for a name an agent already chose ("Russia", "U.S.", "USA", "RU"); None when it is not exactly
    a known country name, alias or code. Never a story scanner — see the module docstring."""
    return _index().get(_norm(text))


def states() -> list[Country]:
    return [c for c in load().values() if c.kind == "state"]


@lru_cache(maxsize=1)
def _iso3_index() -> dict[str, str]:
    return {c.iso3: c.iso2 for c in load().values()}


def iso2_of_iso3(iso3: str) -> str | None:
    """ISO2 for an ISO3 code as the data sources spell it (WB/OWID/IMF use ISO3); None if not in the table."""
    return _iso3_index().get((iso3 or "").strip().upper())
